### ISSUE TITLE
Any readme file for how to use the USB demo?

### ISSUE THREAD

**Issue by raysworld** [RoboMaster/DevelopmentBoard-Examples#7]
How to use the USB demo?
After downloading the demo to the board, if I connect the board with the PC with a USB cable, should the device be recognized as a Serial Port according to the readme of the repository?

**Comment by yu-mei** [comment]
I meet the same question. Have you know how to use the demo now?

**Comment by yu-mei** [comment]
> How to use the USB demo?
> After downloading the demo to the board, if I connect the board with the PC with a USB cable, should the device be recognized as a Serial Port according to the readme of the repository?

I meet the same question. Have you know how to use the demo now?

**Comment by raysworld** [comment]
> > How to use the USB demo?
> > After downloading the demo to the board, if I connect the board with the PC with a USB cable, should the device be recognized as a Serial Port according to the readme of the repository?
> 
> I meet the same question. Have you know how to use the demo now?

Hi, yu-mei, after downloading the demo to the board, the device will be recognized as a serial port. At the beginning my PC did not respond to this device and later I found that there was something wrong with my USB cable. After changing the cable the demo is working now.

**Comment by yu-mei** [comment]
Thanks for your valuable reply. I'll try it again.
